# Étape 1: Build de l'application en mode développement
FROM node:16-alpine
WORKDIR /app

# Copie des fichiers de configuration pour installer les dépendances
COPY package.json ./
COPY package-lock.json ./ 

# Installer les dépendances en forçant la résolution des conflits
RUN npm ci --force

# L'étape de développement n'a pas besoin de NGINX, il utilise le serveur dev Angular
EXPOSE 4200
